### ISSUE TITLE
does not work on firefox

### ISSUE THREAD

**Issue by iimisfito** [tobytorn/crime-morale#1]
getting a blank page on both crime screen and scamming screen
![firefox_xtiXmOFrrg](https://github.com/user-attachments/assets/61f216bd-8039-48f5-8fef-d35a0130480d)
![firefox_dKKUNsMJNZ](https://github.com/user-attachments/assets/4a516370-18ea-4ffe-8af8-b68d02b1c980)

**Comment by tobytorn** [comment]
This script is not compatible with Greasymonkey. Please try Tampermonkey or Violentmonkey.
